In [1]:
import ipcoal
import toytree
import msprime 
import numpy as np

In [76]:
tre = toytree.rtree.unittree(10, 10000)

In [77]:
mod = ipcoal.Model(tre, Ne=10000)

In [78]:
mod.sim_loci(1, 10000)

In [82]:
#mod.draw_genealogies();

In [79]:
c, t = mod.draw_seqview(start=200, end=400, scrollable=True);

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="3940.0px" height="260.0px" viewBox="0 0 3940.0 260.0" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="tb087ceec0a3247a2ad6e18f487edbee4"> r0 r1 r2 r3 r4 r5 <rect x="2849.2499999999964" y="130.75" width="17.449999999999818" height="14.650000000000006" style="

In [42]:
len(tre.idx_dict[84].up)

5

In [52]:
def hello(arg: float.as_integer_ratio = 2):
    return arg

In [57]:
a = {'a': 3, 'b': 4}
sss = "hello {a} world {b}"
sss.format(**a, b=5)

TypeError: format() got multiple values for keyword argument 'b'

In [51]:
float.as_integer_ratio(0.5)

(1, 2)

In [47]:
MINMAX = 10
rng = np.random.default_rng(333)

tre = toytree.rtree.bdtree(50, seed=rng.integers(1e9)).mod.node_scale_root_height(5e6)
tre = tre.set_node_values("Ne",
    {i: rng.uniform(5e4, 5e5) for i in range(tre.nnodes)}
)
ncolors = []
for i in tre.idx_dict:
    if tre.idx_dict[i].is_root() or len(tre.idx_dict[i].up) > MINMAX:
        ncolors.append('orange')
    else:
        ncolors.append('darkteal')
#ncolors = ['orange' if len(tre.idx_dict[i]) >= MINMAX else 'darkteal' for i in tre.idx_dict]
nsizes = [20 if len(tre.idx_dict[i]) > 1 else 0 for i in tre.idx_dict]

tre.draw(
    ts='p', 
    node_colors=ncolors, 
    node_sizes=nsizes, 
    layout='d',
    #node_labels=False,
    width=800,
    edge_type='c',
);

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="800.0px" height="265.0px" viewBox="0 0 800.0 265.0" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="tffc0fc93e6b9483c9b363fe66812f8c2"> 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15 r16 r17 r18 r19 r20 r21 r22 r23 r24 r25 r26 r27 r28 r29 r30 r31 r32 r33 r34 r35 r36 r37 r38 r39 r40 r41 r42 r43 r44 r45 r46 r47 r48 r49 0 2500000 5000000

In [58]:
tre.idx_dict[41].up.height

202480.9075659658

In [23]:
0.05 / 1e-9

50000000.0

In [3]:
tree = toytree.rtree.unittree(10, seed=333, treeheight=2e6)
tree = tree.set_node_values("Ne", {i: np.random.uniform(1e3, 1e4) for i in tree.idx_dict})
tree.draw(ts='p', admixture_edges=(3, 0));

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="350.0px" height="260.0px" viewBox="0 0 350.0 260.0" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="t0ede5ac2d81e4addae72b6e8535c426c"> 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 0 1000000 2000000

In [4]:
model = ipcoal.Model(
    tree=tree, 
    nsamples=4, 
    seed_trees=3, 
    seed_mutations=34,
    subst_model="jc69",
)
model.sim_loci(10, 10)

In [7]:
model.write_loci_to_hdf5('test', '/tmp', diploid=True)

wrote 10 loci to /tmp/test.seqs.hdf5


In [10]:
from ipcoal.io.transformer import Transformer
txf = Transformer(model.seqs, model.alpha_ordered_names, model.alleles, diploid=True)
txf.names

['r0_0',
 'r0_1',
 'r1_0',
 'r1_1',
 'r2_0',
 'r2_1',
 'r3_0',
 'r3_1',
 'r4_0',
 'r4_1',
 'r5_0',
 'r5_1',
 'r6_0',
 'r6_1',
 'r7_0',
 'r7_1',
 'r8_0',
 'r8_1',
 'r9_0',
 'r9_1']

In [17]:
import h5py

with h5py.File("/tmp/test.seqs.hdf5", 'r') as io5:
    print(io5['phymap'].attrs['phynames'])#.keys())



['r0' 'r1' 'r2' 'r3' 'r4' 'r5' 'r6' 'r7' 'r8' 'r9']


In [67]:
model.rng_muts.choice(list(model.alleles.keys()), size=10, replace=True, p=[1, 0.])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
print(model.write_concat_to_phylip())

20 10
r0_0       AAAAAAAAAA
r0_1       AAAAAAAAAA
r1_0       CAAAAACCCA
r1_1       CAAAAACCAA
r2_0       AAACAAAAAA
r2_1       AAACAAAAAA
r3_0       AAAAAAAAAA
r3_1       AAAAAAAAAA
r4_0       AAAAAAAAAA
r4_1       AAAAAAAAAA
r5_0       AACAAAAAAC
r5_1       AACAAAAAAC
r6_0       AAAAACAAAA
r6_1       AAAAACAAAA
r7_0       AAAAAAAAAC
r7_1       AAAAAAAAAC
r8_0       AAAAAAAAAA
r8_1       AAAAAAAAAA
r9_0       ACAACAAAAA
r9_1       ACAACAAAAA


In [10]:
model.ancestral_seq

array([76, 71, 81, 83, 83], dtype=uint8)

In [79]:
model.write_vcf()

CHROM  POS ID REF  ALT  QUAL FILTER INFO FORMAT r0_0  ... r5_0 r5_1 r6_0  \
0      1    1  .      C,A    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
1      2    1  .      C,A    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
2      3    1  .      C,A    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
3      4    1  .      C,A    99   PASS    .     GT  2|2  ...  1|1  1|1  2|2   
4      5    1  .      C,A    99   PASS    .     GT  1|1  ...  1|1  1|1  2|2   

  r6_1 r7_0 r7_1 r8_0 r8_1 r9_0 r9_1  
0  2|2  2|2  2|2  2|2  2|2  1|1  1|1  
1  2|2  2|2  2|2  1|1  1|1  2|2  2|2  
2  2|2  2|2  2|2  2|2  2|2  1|1  1|1  
3  2|2  2|2  2|2  2|2  2|2  2|2  2|2  
4  2|2  2|2  2|2  2|2  2|2  2|2  2|2  

[5 rows x 29 columns]

In [70]:
a = msprime.InfiniteAlleles()

In [74]:
a.asdict()

{}

In [75]:
msprime.BinaryMutationModel().asdict()

{}

In [136]:
np.array(list(b'0123'))#.view(np.uint8)

array([48, 49, 50, 51])

In [117]:
np.array([48], dtype=np.uint8).view(bytes)

ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

In [8]:
dd = {'0': 3, b'0': 4, 0: 5}

In [19]:
ts = msprime.sim_ancestry(samples=2, sequence_length=1000)
mts = msprime.sim_mutations(ts, rate=1e-3, model='binary')
mts.genotype_matrix()#alleles=tuple("ACGT"))

array([[0, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 1]], dtype=int8)

In [20]:
for i in mts.variants():
    if not i:
        print('d')

In [22]:
variant = next(mts.variants())

In [23]:
mts.genotype_matrix()

array([[0, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 1]], dtype=int8)

In [32]:
tuple(msprime.JC69().alleles)

('A', 'C', 'G', 'T')

In [24]:
[variant.alleles[i] for i in variant.genotypes]

['0', '1', '1', '1']

In [132]:
%%timeit
if mts.num_mutations < 1:
    print('hi')
genos = mts.genotype_matrix(alleles=tuple(model.subst_model.alleles))[0]
nalleles = np.unique(genos).size
if not 3 >= nalleles >= 1:
    print('hoo')

39.1 µs ± 3.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [136]:
if mts.num_mutations < 1:
    print('hi')
genos = mts.genotype_matrix(alleles=tuple('ACGT'))[0]
nalleles = np.unique(genos).size
if not 3 >= nalleles >= 1:
    print('hoo')
genos, nalleles

(array([1, 2, 1, 1], dtype=int8), 2)

In [159]:
variants.alleles

('C', 'G')

In [160]:
variants.site.ancestral_state

'C'

In [161]:
variants.alleles.index("C")

0

In [88]:
for v in mts.variants():
    print(v.site.ancestral_state, v.site.mutations)
    print("")

A [{'id': 0, 'site': 0, 'node': 0, 'time': 1.4824434344667796, 'derived_state': 'G', 'parent': -1, 'metadata': b''}]

G [{'id': 1, 'site': 1, 'node': 0, 'time': 2.085562909192505, 'derived_state': 'C', 'parent': -1, 'metadata': b''}]

A [{'id': 2, 'site': 2, 'node': 5, 'time': 2.052162412859526, 'derived_state': 'C', 'parent': -1, 'metadata': b''}]

T [{'id': 3, 'site': 3, 'node': 5, 'time': 2.970444192198931, 'derived_state': 'A', 'parent': -1, 'metadata': b''}]

G [{'id': 4, 'site': 4, 'node': 5, 'time': 1.5487038146390895, 'derived_state': 'C', 'parent': -1, 'metadata': b''}]

G [{'id': 5, 'site': 5, 'node': 4, 'time': 0.43029088265233606, 'derived_state': 'T', 'parent': -1, 'metadata': b''}]

T [{'id': 6, 'site': 6, 'node': 5, 'time': 1.6809942896277354, 'derived_state': 'C', 'parent': -1, 'metadata': b''}]

T [{'id': 7, 'site': 7, 'node': 1, 'time': 0.27137615967812784, 'derived_state': 'A', 'parent': -1, 'metadata': b''}]

T [{'id': 8, 'site': 8, 'node': 0, 'time': 3.109553249489

In [30]:
model.ancestral_seq

array([67, 71, 65, 67, 67], dtype=uint8)

In [31]:
model.seqs

array([[1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 1, 3],
       [1, 2, 0, 3, 3],
       [1, 2, 0, 3, 3],
       [1, 2, 0, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 3, 0, 1, 1],
       [1, 3, 0, 1, 1],
       [2, 2, 2, 1, 1],
       [2, 2, 2, 1, 1]], dtype=uint8)

In [27]:
model.write_vcf()

CHROM  POS ID REF  ALT  QUAL FILTER INFO FORMAT r0_0  ... r5_0 r5_1 r6_0  \
0      1    1  .      G,C    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
1      2    1  .      T,G    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
2      3    1  .      G,A    99   PASS    .     GT  2|2  ...  2|2  2|2  2|2   
3      4    1  .      T,C    99   PASS    .     GT  2|2  ...  1|1  1|1  2|2   
4      5    1  .      T,C    99   PASS    .     GT  1|1  ...  1|1  1|1  2|2   

  r6_1 r7_0 r7_1 r8_0 r8_1 r9_0 r9_1  
0  2|2  2|2  2|2  2|2  2|2  1|1  1|1  
1  2|2  2|2  2|2  1|1  1|1  2|2  2|2  
2  2|2  2|2  2|2  2|2  2|2  1|1  1|1  
3  2|2  2|2  2|2  2|2  2|2  2|2  2|2  
4  2|2  2|2  2|2  2|2  2|2  2|2  2|2  

[5 rows x 29 columns]